[package]
name = "sapphbot"
version = "0.1.0"
authors = ["Haley Owsianko <haley.owsianko@gmail.com>"]
edition = "2018"

[dependencies]
serde_derive = "1.0.80"
serde = "1.0.80"
serde_json = "1.0.33"
reqwest = "0.9.5"
regex = "1.1.0"
